[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "taxjar_integration"
authors = [
    {name = "Frappe Technologies Pvt. Ltd.", email = "hello@frappe.io"}
]
dynamic = ["version"]
description = "Taxjar Integration with ERPNext"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

dependencies = []

[project.urls]
Homepage = "https://github.com/frappe/taxjar_integration"

[tool.bench.dev-dependencies]
frappe = ">=15.0.0"
erpnext = ">=15.0.0"
taxjar = "~=1.9.2"

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 99

[tool.black]
line-length = 99
